using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;

namespace MangaEpubAutomation.Gui;

public sealed class LocalizationManager : INotifyPropertyChanged
{
    private static readonly IReadOnlyDictionary<string, string> Zh = new ReadOnlyDictionary<string, string>(
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "MangaEpubAutomation",
            ["App.GuiTitle"] = "MangaEpubAutomation GUI",
            ["Nav.Run"] = "运行",
            ["Nav.Dependencies"] = "依赖",
            ["Nav.PipelineConfig"] = "流水线配置",
            ["Nav.MergeOrder"] = "合并顺序",
            ["Nav.LogsResult"] = "日志与结果",
            ["Theme.FollowSystem"] = "主题：跟随系统",
            ["Theme.Light"] = "主题：浅色",
            ["Theme.Dark"] = "主题：深色",
            ["Lang.Chinese"] = "语言：中文",
            ["Lang.English"] = "Language: English",

            ["Common.Browse"] = "浏览",
            ["Common.Severity"] = "级别",
            ["Common.Code"] = "代码",
            ["Common.Message"] = "消息",
            ["Common.Chapter"] = "章节",
            ["Common.Order"] = "顺序",
            ["Common.EpubPath"] = "EPUB 路径",
            ["Common.AdvancedJsonEditor"] = "高级 JSON 编辑器",
            ["Common.ReloadJson"] = "重新加载 JSON",
            ["Common.SaveJsonRaw"] = "保存原始 JSON",
            ["Common.Load"] = "加载",
            ["Common.Save"] = "保存",
            ["Common.Add"] = "添加",
            ["Common.Remove"] = "移除",
            ["Common.MoveUp"] = "上移",
            ["Common.MoveDown"] = "下移",

            ["Run.WorkspacePaths"] = "工作区路径",
            ["Run.ScriptPath"] = "脚本路径",
            ["Run.TitleRoot"] = "作品根目录",
            ["Run.SourceDirNameOpt"] = "源目录名（可选）",
            ["Run.DepsConfigPath"] = "依赖配置路径",
            ["Run.ConfigPath"] = "配置路径",
            ["Run.MergeOrderFilePath"] = "合并顺序文件路径",
            ["Run.RuntimeSettings"] = "运行设置",
            ["Run.UpscaleFactor"] = "超分倍率",
            ["Run.Format"] = "格式",
            ["Run.LossyQuality"] = "有损质量",
            ["Run.LogLevel"] = "日志级别",
            ["Run.ExtraGroupsMode"] = "额外分组处理",
            ["Run.ExtraGroupsMode.Ignore"] = "1) 默认：忽略额外分组",
            ["Run.ExtraGroupsMode.ChapterNoMerge"] = "2) 参照话处理，但不合并",
            ["Run.ExtraGroupsMode.ChapterMerge"] = "3) 参照话处理并允许合并（作品名 - 文件夹名）",
            ["Run.DryRun"] = "DryRun",
            ["Run.NoUpscaleProgress"] = "关闭超分进度",
            ["Run.FailOnWarnings"] = "预检警告即失败",
            ["Run.MergePreviewCompact"] = "合并预览紧凑模式",
            ["Run.StagesActions"] = "阶段与操作",
            ["Run.StageUpscale"] = "超分",
            ["Run.StageEpub"] = "EPUB 打包",
            ["Run.StageMerge"] = "总集合并",
            ["Run.GeneratePlan"] = "生成计划",
            ["Run.RunPipeline"] = "运行流水线",
            ["Run.Cancel"] = "取消",
            ["Run.LoadLatestArtifacts"] = "加载最新产物",
            ["Run.LiveProgress"] = "实时进度",
            ["Run.PreflightIssues"] = "预检问题",
            ["Run.MergePreview"] = "合并预览",
            ["Run.PreflightSummaryFmt"] = "错误={0}, 警告={1}, 信息={2}",

            ["Run.Tip.ScriptPath"] = "PowerShell 流水线脚本路径。",
            ["Run.Tip.TitleRoot"] = "单个作品根目录，源目录和输出目录都由此推导。",
            ["Run.Tip.SourceDirName"] = "当候选源目录不唯一时可手动指定。",
            ["Run.Tip.DepsConfigPath"] = "依赖配置 JSON 路径。",
            ["Run.Tip.ConfigPath"] = "流水线配置 JSON 路径。",
            ["Run.Tip.MergeOrderFilePath"] = "用于合并阶段的章节显式顺序文件（可选）。",
            ["Run.Tip.UpscaleFactor"] = "超分倍率，可选 1/2/3/4。",
            ["Run.Tip.Format"] = "超分输出图片格式。",
            ["Run.Tip.LossyQuality"] = "有损质量 1-100，越高体积越大。",
            ["Run.Tip.LogLevel"] = "info：简洁输出，debug：详细诊断。",
            ["Run.Tip.ExtraGroupsMode"] = "针对除默认/单行本外的其他一级目录，选择处理方式。",
            ["Run.Tip.DryRun"] = "仅预演流程，不写入输出文件。",
            ["Run.Tip.NoUpscaleProgress"] = "关闭超分阶段实时进度显示。",
            ["Run.Tip.FailOnWarnings"] = "将预检警告视作阻断错误。",
            ["Run.Tip.MergePreviewCompact"] = "合并顺序预览使用紧凑模式。",
            ["Run.Tip.StageUpscale"] = "执行图片超分阶段。",
            ["Run.Tip.StageEpub"] = "执行分章 EPUB 打包阶段。",
            ["Run.Tip.StageMerge"] = "执行默认分组总集合并阶段。",

            ["Dep.Title"] = "依赖配置",
            ["Dep.LoadForm"] = "加载表单",
            ["Dep.SaveForm"] = "保存表单",
            ["Dep.InitFromTemplate"] = "从模板初始化",
            ["Dep.Paths"] = "依赖路径",
            ["Dep.Progress"] = "进度设置",
            ["Dep.Enabled"] = "启用",
            ["Dep.Repos"] = "依赖仓库",
            ["Dep.MJRepo"] = "MangaJaNaiConverterGui 仓库",
            ["Dep.KccRepo"] = "KCC 仓库",
            ["Dep.CopyRepo"] = "CopyManga Downloader 仓库",
            ["Dep.Tip.PythonExe"] = "MangaJaNai 后端使用的 python 可执行文件路径。",
            ["Dep.Tip.BackendScript"] = "run_upscale.py 的路径。",
            ["Dep.Tip.ModelsDir"] = "MangaJaNai 模型目录路径。",
            ["Dep.Tip.KccExe"] = "KCC 可执行文件路径。",
            ["Dep.Tip.ProgressEnabled"] = "是否在 CLI 中显示实时进度。",

            ["Cfg.Title"] = "流水线配置",
            ["Cfg.LoadForm"] = "加载表单",
            ["Cfg.SaveForm"] = "保存表单",
            ["Cfg.InitViaScript"] = "脚本初始化",
            ["Cfg.PipelineNaming"] = "目录与命名规则",
            ["Cfg.MangaSettings"] = "超分默认设置",
            ["Cfg.KccMain"] = "KCC 主设置（官方参数）",
            ["Cfg.KccProcessing"] = "KCC 图像处理（官方参数）",
            ["Cfg.KccPost"] = "KCC 后处理（官方参数）",
            ["Cfg.MergeMetadata"] = "合并元数据",
            ["Cfg.DefaultUnset"] = "默认（未设置）",
            ["Cfg.Disabled"] = "禁用",
            ["Cfg.Split"] = "拆分",
            ["Cfg.Rotate"] = "旋转",
            ["Cfg.Both"] = "两者都做",
            ["Cfg.Margins"] = "边距",
            ["Cfg.MarginsPageNo"] = "边距 + 页码",
            ["Cfg.Horizontally"] = "仅横向",
            ["Cfg.ImageModeDefault"] = "JPEG/自动（默认）",
            ["Cfg.ImageModePng"] = "PNG（--forcepng）",
            ["Cfg.ImageModeMozJpeg"] = "mozJPEG（--mozjpeg）",
            ["Cfg.SourceDirSuffixToSkip"] = "源目录过滤后缀",
            ["Cfg.OutputDirSuffix"] = "超分输出目录后缀",
            ["Cfg.EpubOutputDirSuffix"] = "EPUB 输出目录后缀",
            ["Cfg.OutputFilenamePattern"] = "输出文件名模板",
            ["Cfg.OverwriteExistingFiles"] = "覆盖已存在文件",
            ["Cfg.UpscaleScaleFactor"] = "默认超分倍率",
            ["Cfg.OutputFormat"] = "默认输出格式",
            ["Cfg.LossyCompressionQuality"] = "默认有损压缩质量",
            ["Cfg.GrayscaleDetectionThreshold"] = "灰度检测阈值",
            ["Cfg.KccDeviceProfile"] = "设备档位（--profile）",
            ["Cfg.KccOutputFormat"] = "输出格式（--format）",
            ["Cfg.KccTargetSizeMb"] = "目标体积 MB（--targetsize）",
            ["Cfg.KccMangaStyle"] = "漫画阅读模式（--manga-style）",
            ["Cfg.KccWebtoonMode"] = "条漫模式（--webtoon）",
            ["Cfg.KccHighQualityMagnification"] = "高质放大（--hq）",
            ["Cfg.KccTwoPanelView"] = "双分屏预览（--two-panel）",
            ["Cfg.KccNoKepub"] = "禁用 KEPUB 后缀（--nokepub）",
            ["Cfg.KccDisableProcessing"] = "禁用图像处理（--noprocessing）",
            ["Cfg.KccForceColor"] = "强制彩色（--forcecolor）",
            ["Cfg.KccDoublePageParser"] = "跨页解析（--splitter）",
            ["Cfg.KccCroppingMode"] = "裁边模式（--cropping）",
            ["Cfg.KccGamma"] = "伽马值（--gamma）",
            ["Cfg.KccInterPanelCrop"] = "分格间裁切（--interpanelcrop）",
            ["Cfg.KccCroppingPower"] = "裁边强度（--croppingpower）",
            ["Cfg.KccPreserveMarginPercent"] = "保留边距百分比（--preservemargin）",
            ["Cfg.KccCroppingMinimumRatio"] = "最小裁边比例（--croppingminimum）",
            ["Cfg.KccJpegQuality"] = "JPEG 质量（--jpeg-quality）",
            ["Cfg.KccImageOutputMode"] = "图像输出模式",
            ["Cfg.KccUpscaleSmallImages"] = "放大小图（--upscale）",
            ["Cfg.KccStretchToResolution"] = "拉伸到分辨率（--stretch）",
            ["Cfg.KccForceBlackBorders"] = "强制黑边（--blackborders）",
            ["Cfg.KccForceWhiteBorders"] = "强制白边（--whiteborders）",
            ["Cfg.KccMaximizeStrips"] = "1x4 转 2x2 条带（--maximizestrips）",
            ["Cfg.KccSpreadShift"] = "跨页偏移（--spreadshift）",
            ["Cfg.KccNoRotateSpreads"] = "跨页不旋转（--norotate）",
            ["Cfg.KccRotateFirstSpread"] = "首跨页旋转（--rotatefirst）",
            ["Cfg.KccAutoLevel"] = "极黑点（--autolevel）",
            ["Cfg.KccDisableAutoContrast"] = "禁用自动对比度（--noautocontrast）",
            ["Cfg.KccColorAutoContrast"] = "彩色自动对比度（--colorautocontrast）",
            ["Cfg.KccEraseRainbow"] = "彩虹条抑制（--eraserainbow）",
            ["Cfg.Language"] = "语言",
            ["Cfg.DescriptionHeader"] = "描述前缀",
            ["Cfg.MetadataContributor"] = "元数据贡献者",
            ["Cfg.IncludeOrderInDescription"] = "描述中包含顺序值",
            ["Cfg.Tip.SourceDirSuffixToSkip"] = "扫描源目录候选时，匹配该后缀的目录会被忽略。",
            ["Cfg.Tip.OutputDirSuffix"] = "超分输出图片目录默认后缀。",
            ["Cfg.Tip.EpubOutputDirSuffix"] = "EPUB 输出目录默认后缀。",
            ["Cfg.Tip.OutputFilenamePattern"] = "超分文件名模板，例如 %filename%-upscaled。",
            ["Cfg.Tip.OverwriteExistingFiles"] = "开启后允许覆盖已存在输出。",
            ["Cfg.Tip.UpscaleScaleFactor"] = "默认超分倍率，建议 1-4。",
            ["Cfg.Tip.OutputFormat"] = "超分阶段默认输出格式（webp/png/jpeg/avif）。",
            ["Cfg.Tip.LossyCompressionQuality"] = "有损压缩质量 1-100，越高体积越大。",
            ["Cfg.Tip.GrayscaleDetectionThreshold"] = "MangaJaNai 灰度检测阈值（0-24）。数值越大越不容易判定为灰度页。",
            ["Cfg.Tip.KccDeviceProfile"] = "KCC 设备档位，例如 KS。",
            ["Cfg.Tip.KccOutputFormat"] = "KCC 输出格式（Auto/MOBI/EPUB/CBZ/KFX/MOBI+EPUB/PDF）。",
            ["Cfg.Tip.KccTargetSizeMb"] = "最大输出体积（MB），留空则遵循 KCC 默认。",
            ["Cfg.Tip.KccMangaStyle"] = "右向左阅读，并启用漫画适配。",
            ["Cfg.Tip.KccWebtoonMode"] = "长条漫画处理模式。",
            ["Cfg.Tip.KccHighQualityMagnification"] = "尝试更高质的放大处理。",
            ["Cfg.Tip.KccTwoPanelView"] = "Panel View 下双屏而非四屏。",
            ["Cfg.Tip.KccNoKepub"] = "EPUB 输出时使用 .epub 而非 .kepub.epub。",
            ["Cfg.Tip.KccDisableProcessing"] = "关闭图像处理，忽略部分 profile/processing 选项。",
            ["Cfg.Tip.KccForceColor"] = "强制保持彩色，不转灰度。",
            ["Cfg.Tip.KccDoublePageParser"] = "跨页解析：0 拆分，1 旋转，2 两者都做。",
            ["Cfg.Tip.KccCroppingMode"] = "裁边模式：0 禁用，1 边距，2 边距+页码。",
            ["Cfg.Tip.KccGamma"] = "伽马值，可填 Auto 或数字。",
            ["Cfg.Tip.KccInterPanelCrop"] = "分格空白裁切：0 禁用，1 仅横向，2 两个方向。",
            ["Cfg.Tip.KccCroppingPower"] = "裁边强度，留空则使用 KCC 默认 1.0。",
            ["Cfg.Tip.KccPreserveMarginPercent"] = "裁边后额外保留的边距百分比。",
            ["Cfg.Tip.KccCroppingMinimumRatio"] = "最小裁切面积比例，留空则使用默认值。",
            ["Cfg.Tip.KccJpegQuality"] = "JPEG 质量 0-95，留空则使用 KCC 默认。",
            ["Cfg.Tip.KccImageOutputMode"] = "KCC 输出图片编码模式。",
            ["Cfg.Tip.KccUpscaleSmallImages"] = "把小于设备分辨率的图片放大。",
            ["Cfg.Tip.KccStretchToResolution"] = "把图片强制拉伸到设备分辨率。",
            ["Cfg.Tip.KccForceBlackBorders"] = "禁用边界自动检测，强制黑边。",
            ["Cfg.Tip.KccForceWhiteBorders"] = "禁用边界自动检测，强制白边。",
            ["Cfg.Tip.KccMaximizeStrips"] = "把 1x4 条带布局转换为 2x2。",
            ["Cfg.Tip.KccSpreadShift"] = "横屏时首页偏移到对侧以对齐跨页。",
            ["Cfg.Tip.KccNoRotateSpreads"] = "启用 splitter 时不旋转跨页。",
            ["Cfg.Tip.KccRotateFirstSpread"] = "splitter 模式下优先旋转首个跨页。",
            ["Cfg.Tip.KccAutoLevel"] = "把出现最频繁的暗色像素当作黑点。",
            ["Cfg.Tip.KccDisableAutoContrast"] = "禁用自动对比度处理。",
            ["Cfg.Tip.KccColorAutoContrast"] = "彩色页也应用自动对比度。",
            ["Cfg.Tip.KccEraseRainbow"] = "减弱彩色电子墨水屏的彩虹纹干扰。",
            ["Cfg.Tip.Language"] = "合并 EPUB 的 language 元数据。",
            ["Cfg.Tip.DescriptionHeader"] = "构建合并 EPUB 描述时使用的前缀。",
            ["Cfg.Tip.MetadataContributor"] = "合并阶段写入的 contributor 值。",
            ["Cfg.Tip.IncludeOrderInDescription"] = "在总集描述中附带 chapter order 值。",

            ["Merge.Title"] = "合并顺序",
            ["Merge.OrderFile"] = "顺序文件",
            ["Merge.GenerateTemplate"] = "生成模板",

            ["Logs.Title"] = "日志与结果",
            ["Logs.Clear"] = "清空日志",
            ["Logs.LoadLatestPlan"] = "加载最新 Plan JSON",
            ["Logs.LoadLatestResult"] = "加载最新 Result JSON",
            ["Logs.LiveLog"] = "实时日志",
            ["Logs.PlanJson"] = "Plan JSON",
            ["Logs.ResultJson"] = "Result JSON",

            ["Status.Idle"] = "空闲",
            ["Status.RunningPlan"] = "正在生成计划...",
            ["Status.RunningPipeline"] = "正在运行流水线...",
            ["Status.Canceled"] = "已取消",
            ["Status.ExitFmt"] = "退出码={0}",
            ["Status.NoPreflight"] = "暂无预检结果。",
            ["Status.MergeNoChapters"] = "Merge 阶段：没有可合并章节。",
            ["Status.MergeRunningFmt"] = "Merge 阶段进行中：正在合并 {0} 章...",
            ["Status.MergeSkippedFmt"] = "Merge 阶段已跳过：{0}",
            ["Status.MergeDoneFmt"] = "Merge 完成：packed={0} skipped={1} failed={2}",

            ["Msg.PreflightHasErrors"] = "预检存在错误，请先修复后再执行。",
            ["Msg.PreflightWarningsTitle"] = "预检警告",
            ["Msg.PreflightWarningsHeader"] = "预检警告：",
            ["Msg.PreflightWarningsContinue"] = "继续执行？",
            ["Msg.MergeConfirmTitle"] = "合并确认",
            ["Msg.MergeConfirmFmt"] = "合并顺序共 {0} 章，是否继续？",
            ["Msg.LaunchFailedFmt"] = "启动进程失败：{0}",
            ["Msg.ProcessExitFmt"] = "进程退出码：{0}",
            ["Msg.EventFmt"] = "[事件:{0}] {1}",
            ["Msg.FileNotFoundFmt"] = "文件不存在：{0}",
            ["Msg.JsonInvalidFmt"] = "JSON 非法：{0}",
            ["Msg.LoadedFileFmt"] = "已加载文件：{0}",
            ["Msg.SavedFileFmt"] = "已保存文件：{0}",
            ["Msg.DepsParseFailedFmt"] = "依赖 JSON 解析失败：{0}",
            ["Msg.ConfigParseFailedFmt"] = "流水线配置解析失败：{0}",
            ["Msg.OpenUrlFailedFmt"] = "打开链接失败：{0}",
            ["Msg.TemplateNotFoundFmt"] = "模板不存在：{0}",
            ["Msg.ScriptNotFound"] = "脚本不存在。",
            ["Msg.InitConfigExitFmt"] = "InitConfig 退出码：{0}",
            ["Msg.MergeOrderPathEmpty"] = "MergeOrderFilePath 为空。",
            ["Msg.MergeOrderSavedFmt"] = "已保存合并顺序：{0}",
            ["Msg.MergePreviewEmpty"] = "当前没有可用的合并预览数据。",
            ["Msg.SelectTitleRoot"] = "选择作品根目录",
            ["Msg.SelectModelsDir"] = "选择 models_dir 目录",
            ["Msg.Validate.ScriptPath"] = "ScriptPath 缺失或无效。",
            ["Msg.Validate.TitleRoot"] = "TitleRoot 缺失或无效。",
            ["Msg.Validate.StageRequired"] = "至少需要选择一个阶段。",
            ["Msg.Validate.StageCombination"] = "非法阶段组合：Upscale + Merge 不能在不跑 Epub 的情况下执行。",
            ["Msg.Validate.DepsJsonFmt"] = "Deps JSON 非法：{0}",
            ["Msg.Validate.ConfigJsonFmt"] = "Config JSON 非法：{0}",
            ["Msg.Validate.MergeOrderJsonFmt"] = "Merge order JSON 非法：{0}",
            ["Msg.MergeOrderMissingChapters"] = "merge order 缺少 chapters[]."
        });

    private static readonly IReadOnlyDictionary<string, string> En = new ReadOnlyDictionary<string, string>(
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "MangaEpubAutomation",
            ["App.GuiTitle"] = "MangaEpubAutomation GUI",
            ["Nav.Run"] = "Run",
            ["Nav.Dependencies"] = "Dependencies",
            ["Nav.PipelineConfig"] = "Pipeline Config",
            ["Nav.MergeOrder"] = "Merge Order",
            ["Nav.LogsResult"] = "Logs & Result",
            ["Theme.FollowSystem"] = "Theme: Follow System",
            ["Theme.Light"] = "Theme: Light",
            ["Theme.Dark"] = "Theme: Dark",
            ["Lang.Chinese"] = "语言：中文",
            ["Lang.English"] = "Language: English",

            ["Common.Browse"] = "Browse",
            ["Common.Severity"] = "Severity",
            ["Common.Code"] = "Code",
            ["Common.Message"] = "Message",
            ["Common.Chapter"] = "Chapter",
            ["Common.Order"] = "Order",
            ["Common.EpubPath"] = "EpubPath",
            ["Common.AdvancedJsonEditor"] = "Advanced JSON Editor",
            ["Common.ReloadJson"] = "Reload JSON",
            ["Common.SaveJsonRaw"] = "Save JSON Raw",
            ["Common.Load"] = "Load",
            ["Common.Save"] = "Save",
            ["Common.Add"] = "Add",
            ["Common.Remove"] = "Remove",
            ["Common.MoveUp"] = "Move Up",
            ["Common.MoveDown"] = "Move Down",

            ["Run.WorkspacePaths"] = "Workspace Paths",
            ["Run.ScriptPath"] = "ScriptPath",
            ["Run.TitleRoot"] = "TitleRoot",
            ["Run.SourceDirNameOpt"] = "SourceDirName (opt)",
            ["Run.DepsConfigPath"] = "DepsConfigPath",
            ["Run.ConfigPath"] = "ConfigPath",
            ["Run.MergeOrderFilePath"] = "MergeOrderFilePath",
            ["Run.RuntimeSettings"] = "Runtime Settings",
            ["Run.UpscaleFactor"] = "UpscaleFactor",
            ["Run.Format"] = "Format",
            ["Run.LossyQuality"] = "LossyQuality",
            ["Run.LogLevel"] = "LogLevel",
            ["Run.ExtraGroupsMode"] = "Extra Group Handling",
            ["Run.ExtraGroupsMode.Ignore"] = "1) Default: ignore extra groups",
            ["Run.ExtraGroupsMode.ChapterNoMerge"] = "2) Process as chapters, no merge",
            ["Run.ExtraGroupsMode.ChapterMerge"] = "3) Process as chapters and merge (Comic - Group)",
            ["Run.DryRun"] = "DryRun",
            ["Run.NoUpscaleProgress"] = "NoUpscaleProgress",
            ["Run.FailOnWarnings"] = "FailOnPreflightWarnings",
            ["Run.MergePreviewCompact"] = "MergePreviewCompact",
            ["Run.StagesActions"] = "Stages & Actions",
            ["Run.StageUpscale"] = "Upscale",
            ["Run.StageEpub"] = "Epub",
            ["Run.StageMerge"] = "Merge",
            ["Run.GeneratePlan"] = "Generate Plan",
            ["Run.RunPipeline"] = "Run Pipeline",
            ["Run.Cancel"] = "Cancel",
            ["Run.LoadLatestArtifacts"] = "Load Latest Artifacts",
            ["Run.LiveProgress"] = "Live Progress",
            ["Run.PreflightIssues"] = "Preflight Issues",
            ["Run.MergePreview"] = "Merge Preview",
            ["Run.PreflightSummaryFmt"] = "Errors={0}, Warnings={1}, Infos={2}",

            ["Run.Tip.ScriptPath"] = "PowerShell pipeline script path.",
            ["Run.Tip.TitleRoot"] = "Root folder of one title. Source and output folders are derived from here.",
            ["Run.Tip.SourceDirName"] = "Optional manual source folder override when multiple candidates exist.",
            ["Run.Tip.DepsConfigPath"] = "Dependency config JSON path.",
            ["Run.Tip.ConfigPath"] = "Pipeline config JSON path.",
            ["Run.Tip.MergeOrderFilePath"] = "Optional explicit chapter order file for merge stage.",
            ["Run.Tip.UpscaleFactor"] = "Upscale factor. Allowed values: 1, 2, 3, 4.",
            ["Run.Tip.Format"] = "Output image format for the upscale stage.",
            ["Run.Tip.LossyQuality"] = "Lossy quality from 1 to 100. Higher means larger files.",
            ["Run.Tip.LogLevel"] = "info: concise output, debug: verbose diagnostics.",
            ["Run.Tip.ExtraGroupsMode"] = "Choose how non-default/non-tankobon top-level groups are processed.",
            ["Run.Tip.DryRun"] = "Preview only. Do not write files.",
            ["Run.Tip.NoUpscaleProgress"] = "Disable realtime upscale progress updates.",
            ["Run.Tip.FailOnWarnings"] = "Treat warnings as blocking errors.",
            ["Run.Tip.MergePreviewCompact"] = "Compact merge preview instead of full chapter list.",
            ["Run.Tip.StageUpscale"] = "Run image super-resolution stage.",
            ["Run.Tip.StageEpub"] = "Run per-chapter EPUB packaging stage.",
            ["Run.Tip.StageMerge"] = "Run merged EPUB stage for default chapters.",

            ["Dep.Title"] = "Dependencies",
            ["Dep.LoadForm"] = "Load Form",
            ["Dep.SaveForm"] = "Save Form",
            ["Dep.InitFromTemplate"] = "Init From Template",
            ["Dep.Paths"] = "Dependency Paths",
            ["Dep.Progress"] = "Progress Settings",
            ["Dep.Enabled"] = "enabled",
            ["Dep.Repos"] = "Dependency Repositories",
            ["Dep.MJRepo"] = "MangaJaNaiConverterGui Repo",
            ["Dep.KccRepo"] = "KCC Repo",
            ["Dep.CopyRepo"] = "CopyManga Downloader Repo",
            ["Dep.Tip.PythonExe"] = "Path to python executable used by MangaJaNai backend.",
            ["Dep.Tip.BackendScript"] = "Path to run_upscale.py.",
            ["Dep.Tip.ModelsDir"] = "Path to MangaJaNai models directory.",
            ["Dep.Tip.KccExe"] = "Path to KCC executable.",
            ["Dep.Tip.ProgressEnabled"] = "Enable realtime progress display in CLI.",

            ["Cfg.Title"] = "Pipeline Config",
            ["Cfg.LoadForm"] = "Load Form",
            ["Cfg.SaveForm"] = "Save Form",
            ["Cfg.InitViaScript"] = "Init Via Script",
            ["Cfg.PipelineNaming"] = "Pipeline Naming",
            ["Cfg.MangaSettings"] = "Manga Upscale Settings",
            ["Cfg.KccMain"] = "KCC Main (official)",
            ["Cfg.KccProcessing"] = "KCC Processing (official)",
            ["Cfg.KccPost"] = "KCC Post-processing (official)",
            ["Cfg.MergeMetadata"] = "Merge Metadata",
            ["Cfg.DefaultUnset"] = "Default (unset)",
            ["Cfg.Disabled"] = "Disabled",
            ["Cfg.Split"] = "Split",
            ["Cfg.Rotate"] = "Rotate",
            ["Cfg.Both"] = "Both",
            ["Cfg.Margins"] = "Margins",
            ["Cfg.MarginsPageNo"] = "Margins + page numbers",
            ["Cfg.Horizontally"] = "Horizontally",
            ["Cfg.ImageModeDefault"] = "JPEG/Auto (default)",
            ["Cfg.ImageModePng"] = "PNG (--forcepng)",
            ["Cfg.ImageModeMozJpeg"] = "mozJPEG (--mozjpeg)",
            ["Cfg.SourceDirSuffixToSkip"] = "SourceDirSuffixToSkip",
            ["Cfg.OutputDirSuffix"] = "OutputDirSuffix",
            ["Cfg.EpubOutputDirSuffix"] = "EpubOutputDirSuffix",
            ["Cfg.OutputFilenamePattern"] = "OutputFilenamePattern",
            ["Cfg.OverwriteExistingFiles"] = "OverwriteExistingFiles",
            ["Cfg.UpscaleScaleFactor"] = "UpscaleScaleFactor",
            ["Cfg.OutputFormat"] = "OutputFormat",
            ["Cfg.LossyCompressionQuality"] = "LossyCompressionQuality",
            ["Cfg.GrayscaleDetectionThreshold"] = "GrayscaleDetectionThreshold",
            ["Cfg.KccDeviceProfile"] = "Device profile (--profile)",
            ["Cfg.KccOutputFormat"] = "Output format (--format)",
            ["Cfg.KccTargetSizeMb"] = "Target size MB (--targetsize)",
            ["Cfg.KccMangaStyle"] = "Manga style (--manga-style)",
            ["Cfg.KccWebtoonMode"] = "Webtoon mode (--webtoon)",
            ["Cfg.KccHighQualityMagnification"] = "Try HQ magnification (--hq)",
            ["Cfg.KccTwoPanelView"] = "Two-panel view (--two-panel)",
            ["Cfg.KccNoKepub"] = "No KEPUB extension (--nokepub)",
            ["Cfg.KccDisableProcessing"] = "Disable processing (--noprocessing)",
            ["Cfg.KccForceColor"] = "Color mode (--forcecolor)",
            ["Cfg.KccDoublePageParser"] = "Double-page parser (--splitter)",
            ["Cfg.KccCroppingMode"] = "Cropping mode (--cropping)",
            ["Cfg.KccGamma"] = "Gamma (--gamma)",
            ["Cfg.KccInterPanelCrop"] = "Inter-panel crop (--interpanelcrop)",
            ["Cfg.KccCroppingPower"] = "Cropping power (--croppingpower)",
            ["Cfg.KccPreserveMarginPercent"] = "Preserve margin % (--preservemargin)",
            ["Cfg.KccCroppingMinimumRatio"] = "Cropping min ratio (--croppingminimum)",
            ["Cfg.KccJpegQuality"] = "JPEG quality (--jpeg-quality)",
            ["Cfg.KccImageOutputMode"] = "Image output mode",
            ["Cfg.KccUpscaleSmallImages"] = "Resize small images (--upscale)",
            ["Cfg.KccStretchToResolution"] = "Stretch to resolution (--stretch)",
            ["Cfg.KccForceBlackBorders"] = "Force black borders (--blackborders)",
            ["Cfg.KccForceWhiteBorders"] = "Force white borders (--whiteborders)",
            ["Cfg.KccMaximizeStrips"] = "1x4 to 2x2 strips (--maximizestrips)",
            ["Cfg.KccSpreadShift"] = "Spread shift (--spreadshift)",
            ["Cfg.KccNoRotateSpreads"] = "No rotate spreads (--norotate)",
            ["Cfg.KccRotateFirstSpread"] = "Rotate first spread (--rotatefirst)",
            ["Cfg.KccAutoLevel"] = "Extreme black point (--autolevel)",
            ["Cfg.KccDisableAutoContrast"] = "Disable autocontrast (--noautocontrast)",
            ["Cfg.KccColorAutoContrast"] = "Color autocontrast (--colorautocontrast)",
            ["Cfg.KccEraseRainbow"] = "Rainbow eraser (--eraserainbow)",
            ["Cfg.Language"] = "Language",
            ["Cfg.DescriptionHeader"] = "DescriptionHeader",
            ["Cfg.MetadataContributor"] = "MetadataContributor",
            ["Cfg.IncludeOrderInDescription"] = "IncludeOrderInDescription",
            ["Cfg.Tip.SourceDirSuffixToSkip"] = "Folder suffix to ignore when scanning source candidates.",
            ["Cfg.Tip.OutputDirSuffix"] = "Suffix appended to generated upscale image folder.",
            ["Cfg.Tip.EpubOutputDirSuffix"] = "Suffix for EPUB output folder.",
            ["Cfg.Tip.OutputFilenamePattern"] = "Filename template used by upscale output.",
            ["Cfg.Tip.OverwriteExistingFiles"] = "If enabled, existing output images can be overwritten.",
            ["Cfg.Tip.UpscaleScaleFactor"] = "Upscale factor used in config.",
            ["Cfg.Tip.OutputFormat"] = "Output image format (webp/png/jpeg/avif).",
            ["Cfg.Tip.LossyCompressionQuality"] = "Lossy compression quality from 1 to 100.",
            ["Cfg.Tip.GrayscaleDetectionThreshold"] = "MangaJaNai grayscale detection threshold (0-24). Higher values make pages less likely to be treated as grayscale.",
            ["Cfg.Tip.KccDeviceProfile"] = "Device profile from KCC --help (for example KS).",
            ["Cfg.Tip.KccOutputFormat"] = "Output format (Auto/MOBI/EPUB/CBZ/KFX/MOBI+EPUB/PDF).",
            ["Cfg.Tip.KccTargetSizeMb"] = "Maximal output size in MB. Leave empty to follow KCC defaults.",
            ["Cfg.Tip.KccMangaStyle"] = "Right-to-left reading and splitting.",
            ["Cfg.Tip.KccWebtoonMode"] = "Webtoon processing mode.",
            ["Cfg.Tip.KccHighQualityMagnification"] = "Try to increase magnification quality.",
            ["Cfg.Tip.KccTwoPanelView"] = "Display two not four panels in Panel View mode.",
            ["Cfg.Tip.KccNoKepub"] = "If output is EPUB, use .epub instead of .kepub.epub.",
            ["Cfg.Tip.KccDisableProcessing"] = "Do not modify image and ignore profile/processing options.",
            ["Cfg.Tip.KccForceColor"] = "Do not convert images to grayscale.",
            ["Cfg.Tip.KccDoublePageParser"] = "Double page parsing mode: 0 Split, 1 Rotate, 2 Both. Default follows KCC config.",
            ["Cfg.Tip.KccCroppingMode"] = "Cropping mode: 0 Disabled, 1 Margins, 2 Margins + page numbers.",
            ["Cfg.Tip.KccGamma"] = "Auto or numeric gamma value.",
            ["Cfg.Tip.KccInterPanelCrop"] = "Crop empty inter-panel sections: 0 Disabled, 1 Horizontal, 2 Both directions.",
            ["Cfg.Tip.KccCroppingPower"] = "Cropping power. Leave empty to follow KCC default (1.0).",
            ["Cfg.Tip.KccPreserveMarginPercent"] = "After crop calculation, add back this percentage margin.",
            ["Cfg.Tip.KccCroppingMinimumRatio"] = "Minimum cropped area ratio. Leave empty for default.",
            ["Cfg.Tip.KccJpegQuality"] = "0-95. Leave empty for KCC default.",
            ["Cfg.Tip.KccImageOutputMode"] = "Image encoding mode used by KCC output files.",
            ["Cfg.Tip.KccUpscaleSmallImages"] = "Resize images smaller than device resolution.",
            ["Cfg.Tip.KccStretchToResolution"] = "Stretch images to device resolution.",
            ["Cfg.Tip.KccForceBlackBorders"] = "Disable autodetection and force black borders.",
            ["Cfg.Tip.KccForceWhiteBorders"] = "Disable autodetection and force white borders.",
            ["Cfg.Tip.KccMaximizeStrips"] = "Turn 1x4 strips into 2x2 strips.",
            ["Cfg.Tip.KccSpreadShift"] = "Shift first page to opposite side in landscape for spread alignment.",
            ["Cfg.Tip.KccNoRotateSpreads"] = "Do not rotate double-page spreads when splitter is enabled.",
            ["Cfg.Tip.KccRotateFirstSpread"] = "Put rotated 2-page spread first in splitter mode.",
            ["Cfg.Tip.KccAutoLevel"] = "Set most common dark pixel value as black point.",
            ["Cfg.Tip.KccDisableAutoContrast"] = "Disable autocontrast processing.",
            ["Cfg.Tip.KccColorAutoContrast"] = "Apply autocontrast to color pages too.",
            ["Cfg.Tip.KccEraseRainbow"] = "Attenuate interfering frequencies for color e-ink rainbow effect.",
            ["Cfg.Tip.Language"] = "Language metadata for merged EPUB.",
            ["Cfg.Tip.DescriptionHeader"] = "Description prefix used when building merged EPUB metadata.",
            ["Cfg.Tip.MetadataContributor"] = "Contributor metadata written by merge stage.",
            ["Cfg.Tip.IncludeOrderInDescription"] = "Include chapter order values in merged EPUB description.",

            ["Merge.Title"] = "Merge Order",
            ["Merge.OrderFile"] = "Order File",
            ["Merge.GenerateTemplate"] = "Generate Template",

            ["Logs.Title"] = "Logs & Result",
            ["Logs.Clear"] = "Clear Logs",
            ["Logs.LoadLatestPlan"] = "Load Latest Plan JSON",
            ["Logs.LoadLatestResult"] = "Load Latest Result JSON",
            ["Logs.LiveLog"] = "Live Log",
            ["Logs.PlanJson"] = "Plan JSON",
            ["Logs.ResultJson"] = "Result JSON",

            ["Status.Idle"] = "Idle",
            ["Status.RunningPlan"] = "Running plan...",
            ["Status.RunningPipeline"] = "Running pipeline...",
            ["Status.Canceled"] = "Canceled",
            ["Status.ExitFmt"] = "Exit={0}",
            ["Status.NoPreflight"] = "No preflight result yet.",
            ["Status.MergeNoChapters"] = "Merge stage: no chapters available to merge.",
            ["Status.MergeRunningFmt"] = "Merge stage running: merging {0} chapter(s)...",
            ["Status.MergeSkippedFmt"] = "Merge stage skipped: {0}",
            ["Status.MergeDoneFmt"] = "Merge completed: packed={0} skipped={1} failed={2}",

            ["Msg.PreflightHasErrors"] = "Preflight has errors. Fix them before execution.",
            ["Msg.PreflightWarningsTitle"] = "Preflight Warnings",
            ["Msg.PreflightWarningsHeader"] = "Preflight warnings:",
            ["Msg.PreflightWarningsContinue"] = "Continue?",
            ["Msg.MergeConfirmTitle"] = "Merge Confirmation",
            ["Msg.MergeConfirmFmt"] = "Merge order has {0} chapters. Continue?",
            ["Msg.LaunchFailedFmt"] = "Failed to launch process: {0}",
            ["Msg.ProcessExitFmt"] = "Process exit code: {0}",
            ["Msg.EventFmt"] = "[event:{0}] {1}",
            ["Msg.FileNotFoundFmt"] = "File not found: {0}",
            ["Msg.JsonInvalidFmt"] = "JSON invalid: {0}",
            ["Msg.LoadedFileFmt"] = "Loaded file: {0}",
            ["Msg.SavedFileFmt"] = "Saved file: {0}",
            ["Msg.DepsParseFailedFmt"] = "Dependencies JSON parse failed: {0}",
            ["Msg.ConfigParseFailedFmt"] = "Pipeline config parse failed: {0}",
            ["Msg.OpenUrlFailedFmt"] = "Failed to open URL: {0}",
            ["Msg.TemplateNotFoundFmt"] = "Template not found: {0}",
            ["Msg.ScriptNotFound"] = "Script not found.",
            ["Msg.InitConfigExitFmt"] = "InitConfig exit code: {0}",
            ["Msg.MergeOrderPathEmpty"] = "MergeOrderFilePath is empty.",
            ["Msg.MergeOrderSavedFmt"] = "Saved merge order: {0}",
            ["Msg.MergePreviewEmpty"] = "No merge preview data available.",
            ["Msg.SelectTitleRoot"] = "Select TitleRoot folder",
            ["Msg.SelectModelsDir"] = "Select models_dir folder",
            ["Msg.Validate.ScriptPath"] = "ScriptPath missing or invalid.",
            ["Msg.Validate.TitleRoot"] = "TitleRoot missing or invalid.",
            ["Msg.Validate.StageRequired"] = "At least one stage must be selected.",
            ["Msg.Validate.StageCombination"] = "Invalid stage combination: Upscale + Merge without EPUB.",
            ["Msg.Validate.DepsJsonFmt"] = "Deps JSON invalid: {0}",
            ["Msg.Validate.ConfigJsonFmt"] = "Config JSON invalid: {0}",
            ["Msg.Validate.MergeOrderJsonFmt"] = "Merge order JSON invalid: {0}",
            ["Msg.MergeOrderMissingChapters"] = "merge order missing chapters[]."
        });

    private string _language = "zh-CN";

    public static LocalizationManager Instance { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    public string CurrentLanguage => _language;

    public string this[string key] => Get(key);

    public void SetLanguage(string language)
    {
        var normalized = string.IsNullOrWhiteSpace(language) ? "zh-CN" : language.Trim();
        if (string.Equals(_language, normalized, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        _language = normalized;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguage)));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
    }

    public string Get(string key)
    {
        if (string.IsNullOrWhiteSpace(key)) return string.Empty;
        var primary = IsChinese() ? Zh : En;
        if (primary.TryGetValue(key, out var value)) return value;
        if (En.TryGetValue(key, out value)) return value;
        if (Zh.TryGetValue(key, out value)) return value;
        return key;
    }

    public string Format(string key, params object[] args)
    {
        var template = Get(key);
        try
        {
            return string.Format(CultureInfo.CurrentUICulture, template, args);
        }
        catch
        {
            return template;
        }
    }

    private bool IsChinese()
    {
        return _language.StartsWith("zh", StringComparison.OrdinalIgnoreCase);
    }
}
